export const SONG_SEED_TITLES = [
  // Original Beatles Tracks
  "A Day in the Life",
  "A Hard Day's Night",
  "A Shot of Rhythm and Blues",
  "A Taste of Honey",
  "Across the Universe",
  "Act Naturally",
  "Ain't She Sweet",
  "All I've Got to Do",
  "All My Loving",
  "All Together Now",
  "All You Need Is Love",
  "And I Love Her",
  "And Your Bird Can Sing",
  "Anna (Go to Him)",
  "Another Girl",
  "Any Time at All",
  "Ask Me Why",
  "Baby It's You",
  "Baby You're a Rich Man",
  "Baby's in Black",
  "Back in the U.S.S.R.",
  "Bad Boy",
  "Because",
  "Being for the Benefit of Mr. Kite!",
  "Besame Mucho",
  "Birthday",
  "Blackbird",
  "Blue Jay Way",
  "Boys",
  "Can't Buy Me Love",
  "Carry That Weight",
  "Chains",
  "Come Together",
  "Continuing Story of Bungalow Bill",
  "Cry Baby Cry",
  "Cry for a Shadow",
  "Day Tripper",
  "Dear Prudence",
  "Devil in Her Heart",
  "Dig a Pony",
  "Dig It",
  "Dizzy Miss Lizzy",
  "Do You Want to Know a Secret",
  "Doctor Robert",
  "Don't Bother Me",
  "Don't Ever Change",
  "Don't Let Me Down",
  "Drive My Car",
  "Eight Days a Week",
  "Eleanor Rigby",
  "Every Little Thing",
  "Everybody's Trying to Be My Baby",
  "Everybody's Got Something to Hide Except Me and My Monkey",
  "Fixing a Hole",
  "Flying",
  "For No One",
  "For You Blue",
  "From Me to You",
  "Get Back",
  "Getting Better",
  "Girl",
  "Glass Onion",
  "Golden Slumbers",
  "Good Day Sunshine",
  "Good Morning Good Morning",
  "Good Night",
  "Got to Get You into My Life",
  "Happiness Is a Warm Gun",
  "Hello, Goodbye",
  "Help!",
  "Helter Skelter",
  "Her Majesty",
  "Here Comes the Sun",
  "Here, There and Everywhere",
  "Hey Bulldog",
  "Hey Jude",
  "Hold Me Tight",
  "Honey Don't",
  "Honey Pie",
  "I Am the Walrus",
  "I Call Your Name",
  "I Don't Want to Spoil the Party",
  "I Feel Fine",
  "I Me Mine",
  "I Need You",
  "I Saw Her Standing There",
  "I Should Have Known Better",
  "I Want to Hold Your Hand",
  "I Want to Tell You",
  "I Want You (She's So Heavy)",
  "I Will",
  "If I Fell",
  "If I Needed Someone",
  "I'll Be Back",
  "I'll Cry Instead",
  "I'll Follow the Sun",
  "I'll Get You",
  "I'm a Loser",
  "I'm Down",
  "I'm Happy Just to Dance with You",
  "I'm Looking Through You",
  "I'm Only Sleeping",
  "I'm So Tired",
  "In My Life",
  "Inner Light",
  "It Won't Be Long",
  "It's All Too Much",
  "It's Only Love",
  "Kansas City / Hey-Hey-Hey-Hey!",
  "Komm, Gib Mir Deine Hand",
  "Lady Madonna",
  "Let It Be",
  "Little Child",
  "Long Long Long",
  "Long Tall Sally",
  "Love Me Do",
  "Love You To",
  "Lovely Rita",
  "Lucy in the Sky with Diamonds",
  "Maggie Mae",
  "Magical Mystery Tour",
  "Martha My Dear",
  "Matchbox",
  "Maxwell's Silver Hammer",
  "Mean Mr. Mustard",
  "Michelle",
  "Misery",
  "Money (That's What I Want)",
  "Mother Nature's Son",
  "Mr. Moonlight",
  "No Reply",
  "Norwegian Wood (This Bird Has Flown)",
  "Not a Second Time",
  "Nowhere Man",
  "Ob-La-Di, Ob-La-Da",
  "Octopus's Garden",
  "Oh! Darling",
  "Old Brown Shoe",
  "One After 909",
  "Only a Northern Song",
  "P.S. I Love You",
  "Paperback Writer",
  "Penny Lane",
  "Piggies",
  "Please Mister Postman",
  "Please Please Me",
  "Polythene Pam",
  "Rain",
  "Real Love",
  "Revolution",
  "Revolution 1",
  "Revolution 9",
  "Rock and Roll Music",
  "Rocky Raccoon",
  "Roll Over Beethoven",
  "Run for Your Life",
  "Savoy Truffle",
  "Sexy Sadie",
  "Sgt. Pepper's Lonely Hearts Club Band",
  "Sgt. Pepper's Lonely Hearts Club Band (Reprise)",
  "She Came in Through the Bathroom Window",
  "She Loves You",
  "She Said She Said",
  "She's a Woman",
  "She's Leaving Home",
  "Slow Down",
  "Something",
  "Strawberry Fields Forever",
  "Sun King",
  "Sure to Fall (In Love with You)",
  "Taxman",
  "Tell Me What You See",
  "Tell Me Why",
  "Thank You Girl",
  "The Ballad of John and Yoko",
  "The End",
  "The Fool on the Hill",
  "The Long and Winding Road",
  "The Night Before",
  "The Word",
  "There's a Place",
  "Things We Said Today",
  "Think for Yourself",
  "This Boy",
  "Ticket to Ride",
  "Till There Was You",
  "Tomorrow Never Knows",
  "Twist and Shout",
  "Two of Us",
  "Wait",
  "We Can Work It Out",
  "What Goes On",
  "What You're Doing",
  "When I Get Home",
  "When I'm Sixty-Four",
  "While My Guitar Gently Weeps",
  "Why Don't We Do It in the Road?",
  "Wild Honey Pie",
  "With a Little Help from My Friends",
  "Within You Without You",
  "Words of Love",
  "Yellow Submarine",
  "Yer Blues",
  "Yes It Is",
  "Yesterday",
  "You Can't Do That",
  "You Know My Name (Look Up the Number)",
  "You Like Me Too Much",
  "You Never Give Me Your Money",
  "You Really Got a Hold on Me",
  "You Won't See Me",
  "You're Going to Lose That Girl",
  "You've Got to Hide Your Love Away",

  // Solo Releases (John, Paul, George, Ringo)
  "Give Peace a Chance",
  "Cold Turkey",
  "Instant Karma!",
  "Mother",
  "Hold On",
  "I Found Out",
  "Working Class Hero",
  "Isolation",
  "Love",
  "God",
  "Power to the People",
  "Imagine",
  "Crippled Inside",
  "Jealous Guy",
  "It's So Hard",
  "I Don't Wanna Be a Soldier Mama",
  "Gimme Some Truth",
  "Oh My Love",
  "How Do You Sleep?",
  "Oh Yoko!",
  "Happy Xmas (War Is Over)",
  "Woman Is the Nigger of the World",
  "New York City",
  "Sunday Bloody Sunday",
  "Luck of the Irish",
  "Angela",
  "Attica State",
  "Mind Games",
  "Tight A$",
  "Aisumasen (I'm Sorry)",
  "Out the Blue",
  "Only People",
  "Meat City",
  "Whatever Gets You Thru the Night",
  "#9 Dream",
  "Steel and Glass",
  "Bless You",
  "Stand by Me",
  "Slippin' and Slidin'",
  "Ain't That a Shame",
  "Be-Bop-A-Lula",
  "Peggy Sue",
  "Just Because",
  "Rock and Roll People",
  "Nobody Loves You (When You're Down and Out)",
  "Borrowed Time",
  "Beautiful Boy (Darling Boy)",
  "Watching the Wheels",
  "Woman",
  "Starting Over",
  "Cleanup Time",
  "Dear Yoko",
  "I'm Losing You",
  "Nobody Told Me",
  "Grow Old with Me",
  "Maybe I'm Amazed",
  "Every Night",
  "Junk",
  "Teddy Boy",
  "Man We Was Lonely",
  "Another Day",
  "Uncle Albert/Admiral Halsey",
  "Too Many People",
  "Dear Boy",
  "Ram On",
  "Monkberry Moon Delight",
  "Eat at Home",
  "The Back Seat of My Car",
  "Hi, Hi, Hi",
  "C Moon",
  "My Love",
  "Live and Let Die",
  "Helen Wheels",
  "Band on the Run",
  "Jet",
  "Bluebird",
  "Mrs. Vandebilt",
  "Let Me Roll It",
  "Nineteen Hundred and Eighty-Five",
  "Junior's Farm",
  "Listen to What the Man Said",
  "Letting Go",
  "Silly Love Songs",
  "Beware My Love",
  "Let 'Em In",
  "Mull of Kintyre",
  "Girls' School",
  "With a Little Luck",
  "London Town",
  "I've Had Enough",
  "Goodnight Tonight",
  "Getting Closer",
  "Arrow Through Me",
  "Wonderful Christmastime",
  "Coming Up",
  "Temporary Secretary",
  "Waterfalls",
  "Ebony and Ivory",
  "Take It Away",
  "Here Today",
  "Pipes of Peace",
  "Say Say Say",
  "So Bad",
  "No More Lonely Nights",
  "Spies Like Us",
  "Press",
  "Only Love Remains",
  "Once Upon a Long Ago",
  "My Brave Face",
  "Figure of Eight",
  "Put It There",
  "Hope of Deliverance",
  "Off the Ground",
  "C'mon People",
  "Young Boy",
  "The World Tonight",
  "Beautiful Night",
  "From a Lover to a Friend",
  "Driving Rain",
  "Fine Line",
  "Jenny Wren",
  "Dance Tonight",
  "Ever Present Past",
  "House of Wax",
  "My Valentine",
  "New",
  "Queenie Eye",
  "Early Days",
  "Save Us",
  "Fuh You",
  "Come On to Me",
  "I Don't Know",
  "Find My Way",
  "Deep Deep Feeling",
  "Women and Wives",
  "Lavatory Lil",
  "My Sweet Lord",
  "What Is Life",
  "Isn't It a Pity",
  "Wah-Wah",
  "Beware of Darkness",
  "All Things Must Pass",
  "Ballad of Sir Frankie Crisp",
  "Awaiting on You All",
  "Apple Scruffs",
  "Hear Me Lord",
  "Bangla Desh",
  "Give Me Love (Give Me Peace on Earth)",
  "Don't Let Me Wait Too Long",
  "Sue Me, Sue You Blues",
  "Living in the Material World",
  "Be Here Now",
  "The Lord Loves the One (That Loves the Lord)",
  "Dark Horse",
  "Ding Dong, Ding Dong",
  "Far East Man",
  "You",
  "This Guitar (Can't Keep from Crying)",
  "Crackerbox Palace",
  "True Love",
  "Pure Smokey",
  "Blow Away",
  "Soft-Hearted Hana",
  "Faster",
  "Love Comes to Everyone",
  "Not Guilty",
  "Here Comes the Moon",
  "All Those Years Ago",
  "Teardrops",
  "Wake Up My Love",
  "Blood from a Clone",
  "Save the World",
  "That's the Way It Goes",
  "Cloud 9",
  "Got My Mind Set on You",
  "When We Was Fab",
  "Devil's Radio",
  "This Is Love",
  "Cheer Down",
  "Any Road",
  "Rising Sun",
  "Stuck Inside a Cloud",
  "Marwa Blues",
  "Pisces Fish",
  "Looking for My Life",
  "It Don't Come Easy",
  "Early 1970",
  "Back Off Boogaloo",
  "Photograph",
  "You're Sixteen",
  "Oh My My",
  "I'm the Greatest",
  "Sunshine Life for Me",
  "Six O'Clock",
  "Only You (And You Alone)",
  "No No Song",
  "Snookeroo",
  "A Dose of Rock 'n' Roll",
  "Hey! Baby",
  "Wings",
  "Lipstick Traces",
  "Wrack My Brain",
  "Private Property",
  "In My Car",
  "Weight of the World",
  "Don't Go Where the Road Don't Go",
  "La De Da",
  "Never Without You",
  "Liverpool 8",
  "Walk with You",
  "Anthem",
  "Rory and the Hurricanes",
  "Postcards from Paradise",
  "Give More Love",
  "What's My Name",
  "Here's to the Nights"
];
